clean:
	rm -f *.fasl
	rm -f */*.fasl
	rm -f */*/*.fasl
	rm -f */*/*/*.fasl
	rm -f */*/*/*/*.fasl
	rm -f *~
	rm -f */*~
	rm -f */*/*~
	rm -f */*/*/*~
	rm -f */*/*/*/*~
	rm -r -f test2
	rm -f autoloads.out
